# Generated by Django 5.1.6 on 2025-03-25 02:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_genero_pelicula_usuario_reseña_recomendacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseña',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='ano_estreno',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='director',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='generos',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='popularidad',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='reparto',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='sinopsis',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='reseña',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='comentario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.pelicula')),
            ],
        ),
    ]
