# Generated by Django 5.1.6 on 2025-03-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_interaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula_id', models.IntegerField()),
                ('accion', models.CharField(max_length=255)),
                ('reseña', models.TextField()),
                ('calificacion', models.IntegerField()),
            ],
        ),
    ]
